version: '3'

services:

  proxy:
    build: ./nginx
    image: yuttasakcom/node-proxy:1.0
    container_name: proxy
    networks:
      - proxy
    ports:
      - "8000:80"
    restart: always

  apis:
    build: .
    image: yuttasakcom/node-apis:1.0.0
    container_name: apis
    networks:
      - proxy
    restart: always

networks:
  proxy:
    driver: bridge
