version: '3'

services:

  proxy:
    build: ./nginx
    image: yuttasakcom/proxy:1.0
    container_name: proxy
    networks:
      - proxy
    ports:
      - "8000:80"
    restart: always

  nodees6:
    build: .
    image: yuttasakcom/nodees6:1.0.0
    container_name: nodees6
    networks:
      - proxy
    restart: always

networks:
  proxy:
    driver: bridge
